import { NgModule } from '@angular/core';
import { MatGridListModule, MatDialogModule, MatFormFieldModule, MatButtonModule, MatInputModule, MatTableModule, MatPaginatorModule, MatSortModule, MatProgressSpinnerModule, MatButtonToggleModule, MatIconModule, MatMenuModule, MatSelectModule, MatToolbarModule, MatExpansionModule, MatCheckbox, MatCheckboxModule, MatSidenavModule, MatDividerModule, MatSnackBarContainer, MatSnackBarModule, MatSlideToggleModule, MatListModule, MatCardModule, MatChipsModule, MatStepperModule, MatTabsModule, MatProgressBarModule, MatRadioModule, MatTooltipModule } from '@angular/material';
import { FormsModule } from '@angular/forms';
import { FlexLayoutModule } from '@angular/flex-layout';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { CommonModule } from '@angular/common';
@NgModule({

  imports: [   
    CommonModule,
    MatInputModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatProgressSpinnerModule,
    FlexLayoutModule,
    MatButtonToggleModule,
    MatIconModule,
    MatMenuModule,
    MatSelectModule,
    MatToolbarModule,
    MatGridListModule,
    MatButtonModule,
    MatFormFieldModule,
    FormsModule,
    MatDialogModule,
    MatExpansionModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatDividerModule,
    MatGridListModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatListModule,
    ScrollingModule,
    MatCardModule,
    MatChipsModule,
    MatTabsModule,
    MatProgressBarModule,
    MatStepperModule,
    MatRadioModule,
    MatProgressSpinnerModule,
    MatTooltipModule
  ],
  exports: [
    MatMenuModule,
    FormsModule,
    MatDialogModule, 
    MatFormFieldModule, 
    MatButtonModule,
    MatInputModule,
    MatIconModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatProgressSpinnerModule,
    FlexLayoutModule,
    MatButtonToggleModule,
    MatSelectModule,
    MatToolbarModule,
    MatGridListModule,
    MatExpansionModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatDividerModule,
    MatGridListModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatListModule,
    ScrollingModule,
    MatCardModule,
    MatChipsModule,
    MatStepperModule,
    MatTabsModule,
    MatRadioModule,
    MatProgressSpinnerModule,
    MatTooltipModule
    ]
})
export class MaterialModule {}